export { XaraGeoClient } from "./client";
  export type {
    XaraGeoClientConfig,
    SpatialEntity,
    CreateSpatialEntityParams,
    NearbySearchParams,
    PolygonSearchParams,
    Parcel,
    CreateParcelParams,
    CheckParcelOverlapParams,
    ParcelVersion,
    CreateParcelVersionParams,
    ParcelSplitParams,
    ParcelSplitResult,
    ParcelMergeParams,
    ParcelMergeResult,
    ParcelLineageEntry,
    SpatialEvent,
    GetSpatialEventsParams,
    H3StatsParams,
    H3Stat,
    ClusterParams,
    ClusterResult,
    HealthStatus,
    XaraApiError,
    Location,
    LocationResolveResult,
    BoundaryMatch,
    BoundaryResolveResult,
    LocationSearchResult,
    DistanceParams,
    DistanceResult,
    NearbyRoadsParams,
    Road,
    NearbyRoadsResult,
    GSIDEntry,
    CreateGSIDParams,
    GSIDResolveResult,
    GraphNode,
    CreateGraphNodeParams,
    GraphEdge,
    CreateGraphEdgeParams,
    GraphChildrenResult,
    GraphParentsResult,
    GraphConnectedResult,
    GraphNodeDetailResult,
  } from "./types";
  export {
    XaraGeoError,
    XaraAuthError,
    XaraNotFoundError,
    XaraValidationError,
    XaraRateLimitError,
  } from "./errors";
  